/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-120324-g85ac589211-20250720"
#endif /* AVUTIL_FFVERSION_H */
